import "./global.scss";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
  manifest: "/manifest.json",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link rel="manifest" href="/manifest.json" />
      <body>
        <div id="root">{children}</div>
      </body>
    </html>
  );
}
